[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aaltoes-cv1"
version = "0.1.0"

[tool.setuptools]
packages = ["utils", "EITL_Net.utils", "EITL_Net.nets"]
