train:
  batch_size: 16
  device: cuda
  n_epochs: 100
  workers: 12
  start_epoch: 23
  best_epoch: 23
dataset: "~/workspace/aaltoes_cv1/kaggle_aaltoes_cv1_proper"
test_dataset: "~/workspace/aaltoes_cv1/kaggle_aaltoes_cv1/test"
use_cudnn: false
